/**
 * Attendee share metadata helpers — favicon + Open Graph titles.
 *
 * Favicon is always the SHOW logo (never a room branding override).
 * Open Graph images are generated by colocated opengraph-image.tsx routes.
 */

import type { Metadata } from 'next'
import type { EffectiveBranding } from '@/types'

const DEFAULT_FAVICON = '/favicon.ico'
const DEFAULT_APPLE_ICON = '/onda-operator-icon.png'

/** Show-level favicon from logoUrl; Onda defaults when unset. */
export function attendeeFaviconIcons(
  showBranding: Pick<EffectiveBranding, 'logoUrl'> | null | undefined,
): NonNullable<Metadata['icons']> {
  const logo = showBranding?.logoUrl?.trim()
  if (!logo) {
    return {
      icon: [{ url: DEFAULT_FAVICON }],
      apple: [{ url: DEFAULT_APPLE_ICON }],
    }
  }
  return {
    icon: [{ url: logo }],
    apple: [{ url: logo }],
  }
}

export function attendeePageMetadata(opts: {
  title: string
  description?: string
  /** Always pass SHOW branding — not room-effective branding. */
  showBranding: Pick<EffectiveBranding, 'logoUrl'> | null | undefined
}): Metadata {
  const description =
    opts.description?.trim() ||
    'Live translation, captions, and session notes powered by cre8ion Onda.'

  return {
    title: opts.title,
    description,
    icons: attendeeFaviconIcons(opts.showBranding),
    openGraph: {
      title: opts.title,
      description,
      type: 'website',
      // og:image comes from opengraph-image.tsx on each attendee route
    },
    twitter: {
      card: 'summary_large_image',
      title: opts.title,
      description,
    },
  }
}
